### ISSUE TITLE
Cmany displays python errors after unsuccessful build

### ISSUE THREAD

**Issue by nshcat** [biojppm/cmany#3]
Hello,
I really enjoy using your tool. The only thing that kinda irks me is that while developing, compiler errors are not uncommon, especially when doing meta programming, but errors during the compilation make `cmany` spew out (i assume) a long python exception stack trace. I see that this is just a minor inconvenience, but I don't see any additional value in showing the internal stack trace of cmany. Is there a way to disable this?

Thanks in advance, your tool is great!

P.S.: The stack trace I receive on my system (ArchLinux, up-to-date) is shown in [this pastebin.](https://pastebin.com/04r6Mwwn)

**Comment by biojppm** [comment]
Thanks!

You're right, the trace is ugly. I've left it there because in a way that really makes it evident something failed, and I was focusing on getting cmany right before dealing with informative error handling. So I just threw exceptions without catching them. As a downside, the trace does confuse the users (and me too), making it less evident whether the compilation or cmany itself failed.

When I get an opportunity, I'll improve how cmany deals with failed compilations it by printing a red error message; that performs the same function without it being so ugly.
